name: Sei Zan Mineral Water
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b2b4b3'
    - '#eef7fe'
    - '#020202'
    - '#47504f'
    - '#232522'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.7496683273930103
  rhythmicContrast: 0.75
purpose: []
