name: Seizan Natural Mineral Water
favicon: null
layout_spectrum: 0.5027
typography_spectrum: 0.50505
title: >-
  Drink for Better Health, Drink healthy water: Drink Seizan Natural Mineral
  Water
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-80832403-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8dcdb'
    - '#adbbaa'
    - '#8c9560'
    - '#535756'
    - '#272d2b'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
