name: Sei Zan Mineral Water
favicon: null
layout_spectrum: 0.74211
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8dcdb'
    - '#adbbaa'
    - '#8c9560'
    - '#535756'
    - '#272d2b'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
